variables:
    http_proxy: "http://proxy.bbn.hp.com:8080/"
    https_proxy: "http://proxy.bbn.hp.com:8080/"

stable:
    image: scorpil/rust:stable
    script:
        - cargo build
        - cargo test

nightly:
    image: scorpil/rust:nightly
    script:
        - cargo build
        - cargo test
